/*
   This file has been generated by IDA.
   It contains local type definitions from
   the type library 's1proto'
*/

#define __int8 char
#define __int16 short
#define __int32 int
#define __int64 long long

/* 1 */
enum MEMMAP
{
  CARTRIDGE = 0x0,
  CARTRIDGESZ = 0x7FFFF,
  CARTRAM = 0x80000,
  WORKRAM = 0xFF0000,
  WORKRAMSZ = 0xFFFFFF,
};

/* 2 */
struct __attribute__((packed)) __attribute__((aligned(1))) obj
{
  char No;
  char Render;
  __int16 Tile;
  int Pat;
  __int16 X;
  __int16 YScr;
  __int16 Y;
  __int16 YSub;
  __int16 XSpeed;
  __int16 YSpeed;
  __int16 Momentum;
  char YRad;
  char XRad;
  char XRender;
  char Priority;
  char Frame;
  char AnimFrame;
  char Anim;
  char LastAnim;
  char FrameTimer;
  char FrameMirr;
  char Collision;
  char ColliCnt;
  char Status;
  char Respawn;
  char Action;
  char SubAction;
  __int16 Angle;
  char Args;
  char field_29;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char field_30;
  char field_31;
  char field_32;
  char field_33;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char field_3E;
  char field_3F;
  char Size;
};

/* 4 */
enum SOUND
{
  BGMNO_GHZ = 0x81,
  BGMNO_LZ = 0x82,
  BGMNO_MZ = 0x83,
  BGMNO_SLZ = 0x84,
  BGMNO_SZ = 0x85,
  BGMNO_CWZ = 0x86,
  BGMNO_INVINC = 0x87,
  BGMNO_1UP = 0x88,
  BGMNO_SPECIAL = 0x89,
  BGMNO_TITLE = 0x8A,
  BGMNO_ENDING = 0x8B,
  BGMNO_BOSS = 0x8C,
  BGMNO_FINAL = 0x8D,
  BGMNO_ZONECLR = 0x8E,
  BGMNO_GAMEOVER = 0x8F,
  BGMNO_CONTINUE = 0x90,
  BGMNO_CREDITS = 0x91,
  SFXNO_JUMP = 0xA0,
  SFXNO_UNK_A1 = 0xA1,
  SFXNO_UNK_A2 = 0xA2,
  SFXNO_DEATH = 0xA3,
  SFXNO_SKID = 0xA4,
  SFXNO_BOMBHIT = 0xA5,
  SFXNO_SPIKEDMG = 0xA6,
  SFXNO_PUSHING = 0xA7,
  SFXNO_WARP = 0xA8,
  SFXNO_UNK_A9 = 0xA9,
  SFXNO_SPLASH = 0xAA,
  SFXNO_UNK_AB = 0xAB,
  SFXNO_BOSSHIT = 0xAC,
  SFXNO_POP1 = 0xAD,
  SFXNO_FIREBALL = 0xAE,
  SFXNO_GETSHIELD = 0xAF,
  SFXNO_UNK_B0 = 0xB0,
  SFXNO_UNK_B1 = 0xB1,
  SFXNO_UNK_B2 = 0xB2,
  SFXNO_UNK_B3 = 0xB3,
  SFXNO_BUMPER = 0xB4,
  SFXNO_RING = 0xB5,
  SFXNO_SPIKES = 0xB6,
  SFXNO_RUMBLE = 0xB7,
  SFXNO_UNK_B8 = 0xB8,
  SFXNO_COLLAPSE1 = 0xB9,
  SFXNO_UNK_BA = 0xBA,
  SFXNO_DOOR = 0xBB,
  SFXNO_LAUNCH = 0xBC,
  SFXNO_HEAVYHIT = 0xBD,
  SFXNO_SPIN = 0xBE,
  SFXNO_UNK_BF = 0xBF,
  SFXNO_WINGFLAP = 0xC0,
  SFXNO_POP2 = 0xC1,
  SFXNO_POP3 = 0xC2,
  SFXNO_EXPLODE1 = 0xC3,
  SFXNO_EXPLODE2 = 0xC4,
  SFXNO_TALLYDONE = 0xC5,
  SFXNO_LOSERINGS = 0xC6,
  SFXNO_CHAINPING = 0xC7,
  SFXNO_FLAME = 0xC8,
  SFXNO_UNK_C9 = 0xC9,
  SFXNO_UNK_CA = 0xCA,
  SFXNO_COLLAPSE2 = 0xCB,
  SFXNO_SPRING = 0xCC,
  SFXNO_BUTTON = 0xCD,
  SFXNO_RINGLEFT = 0xCE,
  SFXNO_GOAL = 0xCF,
  SNDCMD_FADE = 0xE0,
  SNDCMD_UNK = 0xE1,
  SNDCMD_FAST = 0xE2,
  SNDCMD_SLOW = 0xE3,
};

/* 5 */
enum ERRNO
{
  ERRNO_BUS = 0x2,
  ERRNO_ILLEGAL = 0x4,
  ERRNO_ADDRESS = 0x6,
  ERRNO_ZERODIV = 0x8,
  ERRNO_CHKINST = 0xA,
  ERRNO_TRAPV = 0xC,
  ERRNO_PRIVILEGE = 0xE,
  ERRNO_TRACE = 0x10,
  ERRNO_LINE1010 = 0x12,
  ERRNO_LINE1111 = 0x14,
  ERRNO_GENERIC = 0x15,
};

/* 6 */
enum VBNO
{
  VBCMD_NULL = 0x0,
  VBCMD_LOGO = 0x2,
  VBCMD_TITLE = 0x4,
  VBCMD_UNK = 0x6,
  VBCMD_LEVEL = 0x8,
  VBCMD_SPECIAL = 0xA,
  VBCMD_LVLSTART = 0xC,
  VBCMD_TIMER = 0xE,
  VBCMD_PAUSE = 0x10,
  VBCMD_PALETTE = 0x12,
};

/* 7 */
enum GMNO
{
  GMNO_LOGO = 0x0,
  GMNO_TITLE = 0x4,
  GMNO_DEMO = 0x8,
  GMNO_LEVEL = 0xC,
  GMNO_SPECIAL = 0x10,
};

/* 8 */
struct play
{
  _BYTE gap0[20];
  __int16 Momentum;
  char YRad;
  char XRad;
  char XDisp;
  char Priority;
  char Frame;
  char AnimFrame;
  char Anim;
  char AnimPrevious;
  char AnimSpeed;
  char field_1F;
  char field_20;
  char field_21;
  char Status;
  char field_23;
  char Action;
  char SubAction;
  char Angle;
  char field_27;
  char Argument;
  char field_29;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  __int16 Timeout;
  __int16 Invincible;
  __int16 Speedup;
  char FootFront;
  char FootBack;
  __int16 YDeath;
  __int16 LocalTimer;
  char Jump;
  char OnObject;
  char Locked;
  __attribute__((packed)) __attribute__((aligned(1))) __int16 field_3F;
  char field_41;
  char field_42;
  char field_43;
  char field_44;
  char field_45;
};

/* 9 */
enum ZONENO
{
  ZONENO_GHZ = 0x0,
  ACT1 = 0x0,
  ZONENO_LZ = 0x1,
  ACT2 = 0x1,
  ZONENO_MZ = 0x2,
  ACT3 = 0x2,
  ZONENO_SLZ = 0x3,
  ACT4 = 0x3,
  ZONENO_SZ = 0x4,
  ZONENO_CWZ = 0x5,
  ZONENO_UNK = 0x6,
  ZONENO_SPECIAL = 0x7,
};

/* 10 */
enum ARTNO
{
  ARTNO_BOSS = 0x11,
  ARTNO_LVLEND = 0x12,
  ARTNO_SPECIAL = 0x14,
};

/* 11 */
struct __attribute__((packed)) __attribute__((aligned(1))) levelhead
{
  _BYTE gap0;
  __int16 field_1;
};

/* 12 */
enum TXTCODE
{
  _1 = 0x1,
  _2 = 0x2,
  _3 = 0x3,
  _Y = 0xF,
  _Z = 0x10,
  _A = 0x11,
  _B = 0x12,
  _C = 0x13,
  _D = 0x14,
  _E = 0x15,
  _F = 0x16,
  _G = 0x17,
  _H = 0x18,
  _I = 0x19,
  _J = 0x1A,
  _K = 0x1B,
  _L = 0x1C,
  _M = 0x1D,
  _N = 0x1E,
  _O = 0x1F,
  _P = 0x20,
  _Q = 0x21,
  _R = 0x22,
  _S = 0x23,
  _T = 0x24,
  _U = 0x25,
  _V = 0x26,
  _W = 0x27,
  _X = 0x28,
  __ = 0xFF,
};

/* 13 */
enum OBJNO
{
  OBJNO_NULL = 0x0,
  OBJNO_PLAYER = 0x1,
  OBJNO_PLAYSPECIAL = 0x9,
  OBJNO_FIREBALL = 0x14,
  OBJNO_BALLBOMB = 0x20,
  OBJNO_MISSILE = 0x23,
  OBJNO_BOMBHIT = 0x24,
  OBJNO_RING = 0x25,
  OBJNO_LIGHTEXPL = 0x27,
  OBJNO_MONITORITEM = 0x2E,
  OBJNO_TITLECARD = 0x34,
  OBJNO_SPREADFIRE = 0x35,
  what = 0x36,
  OBJNO_RINGLOSS = 0x37,
  OBJNO_SHIELD = 0x38,
  OBJNO_GAMEOVER = 0x39,
  OBJNO_BOSS = 0x3D,
  OBJNO_ENEMYLADYBUG = 0x40,
  OBJNO_BOSSWEAPONS = 0x48,
  OBJNO_WARP = 0x4A,
  OBJNO_GEYSERSPAWN = 0x4C,
};

/* 14 */
enum VDPSTAT
{
  PAL = 0x0,
  DMA = 0x1,
  HBLANKING = 0x2,
  VBLANKING = 0x3,
  ODDFRAME = 0x4,
  SPRITE_COLLIDE = 0x5,
  SPRITE_OVERFLOW = 0x6,
  VBLANK_PENDING = 0x7,
  FIFO_FULL = 0x8,
  FIFO_EMPTY = 0x9,
};

/* 15 */
enum VDPCMD
{
  VRAMREAD = 0x0,
  VSRAMREAD = 0x10,
  CRAMREAD = 0x20,
  VRAMCOPY = 0xC0,
  VRAMWRITE = 0x40000000,
  VSRAMWRITE = 0x40000010,
  VRAMDMA = 0x40000080,
  VSRAMDMA = 0x40000090,
  CRAMWRITE = 0xC0000000,
  CRAMDMA = 0xC0000080,
};

/* 16 */
enum SYSTEM
{
  HBLANK_VBLANK_ENABLE = 0x2300,
};

/* 20 */
enum OBJSTAT
{
  STAT_XDIR = 0x0,
  STAT_YDIR = 0x1,
  STAT_UNK2 = 0x2,
  STAT_LIFTING = 0x3,
  STAT_UNK4 = 0x4,
  STAT_PUSHED = 0x5,
  STAT_UNK6 = 0x6,
  STAT_KILLED = 0x7,
};

/* 21 */
enum OBJREND
{
  REND_XMIRR = 0x0,
  REND_YMIRR = 0x1,
  REND_CAMOFF = 0x2,
  REND_CAMOFF2 = 0x3,
  REND_HEIGHT = 0x4,
  REND_RAW = 0x5,
  REND_BEHIND = 0x6,
  REND_TOGGLE = 0x7,
};

/* 22 */
struct __attribute__((packed)) __attribute__((aligned(1))) snd
{
  char Priority;
  char DelayCnt;
  char Tempo;
  char Pause;
  char Fadeout;
  char FadeoutCnt;
  char FadeoutTime;
  char UserFlag;
  char Rythm;
  char CurrentSnd;
  char QueueA;
  char QueueB;
  char QueueC;
  char field_D;
  char IntrumentMode;
  _BYTE gapF[9];
  int field_18;
  int field_1C;
  int field_20;
  char FadeinCnt;
  char FadeinTime;
  char SndImportant;
  char TempoChg;
  char TempoSpeedup;
  char TempoSpeedupf;
  char field_2A;
  char field_2B;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char field_30;
  char field_31;
  char field_32;
  char field_33;
  char field_34;
  char field_35;
  char field_36;
  char field_37;
  char field_38;
  char field_39;
  char field_3A;
  char field_3B;
  char field_3C;
  char field_3D;
  char field_3E;
  char field_3F;
  char Track;
};

/* 23 */
struct __attribute__((packed)) __attribute__((aligned(1))) objentr
{
  __int16 X;
  __int16 Y;
  char ID;
  char Argument;
  char Save;
  char Size;
  char field_8;
};

/* 24 */
struct channel
{
  char Rythm;
  char MusFM1;
  char MusFM2;
  char MusFM3;
  char MusFM4;
  char MusFM5;
  char MusFM6;
  char MusPSG1;
  char MusPSG2;
  char MusPSG3;
  char SfxFM3;
  char SfxFM4;
  char SfxFM5;
  char SfxPSG1;
  char SfxPSG2;
  char SfxPSG3;
  char SpcFM4;
  char SpcPSG3;
  char SfxImportant;
};

/* 25 */
struct __attribute__((packed)) __attribute__((aligned(1))) track
{
  char Flags;
  char Channel;
  __int16 Tempo;
  int DataPtr;
  char Transpose;
  char Volume;
  char Pan;
  char Instrument;
  char PSGEnvIndex;
  char StackPtr;
  char DurCntr;
  char SavedDuration;
  char SavedPCM;
  char Freq;
  char NoteTimeout;
  char MasterTimeout;
  char ModulationPtr;
  char ModulationWait;
  char ModulationSpeed;
  char ModulationDelta;
  char ModulationSteps;
  char field_19;
  char field_1A;
  char field_1B;
  char field_1C;
  char field_1D;
  char field_1E;
  char field_1F;
  char field_20;
  char field_21;
  char field_22;
  char field_23;
  char field_24;
  char field_25;
  char field_26;
  char field_27;
  char RepeatCntr;
  char field_29;
  __int16 field_2A;
  char field_2C;
  char field_2D;
  char field_2E;
  char field_2F;
  char SIZE;
};

/* 26 */
enum PHYSSTAT
{
  PHYS_DIR = 0x0,
  PHYS_AIRBORNE = 0x1,
  PHYS_ROLLING = 0x2,
  PHYS_LIFTED = 0x3,
  PHYS_ROLLJUMP = 0x4,
  PHYS_PUSH = 0x5,
  PHYS_WATER = 0x6,
  PHYS_KILLED = 0x7,
};

